variable "project_id" {}
variable "gcp_auth_file" {}
variable "region" {}
variable "zone" {}
variable "enable_apis" {}
variable "disable_services_on_destroy" {}
variable "disable_dependent_services" {}
variable "cluster_machine_type" {}
variable "db_tier" {}
variable "metabase_helm_version" {}
variable "airflow_helm_version" {}
variable "airflow_default_tag" {}
variable "airflow_version" {}
variable "airflow_dag_repo" {}
variable "airflow_dag_branch" {}
variable "airflow_dag_dir" {}
variable "airflow_gitSshKey" {}
